version: "3.8"

services:
  # .NetApi service
  web_api:
    image: docker.io/library/winestoreapi:latest
    container_name: dotnet_api
    build:
      context: .
      dockerfile: Dockerfile
    command: dotnet watch run
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://localhost//*:8080
    ports:
      - "5000:80"
    env_file:
      - .env
    volumes:
      - .:/app