version: "3.8"

services:
  # .NetApi service
  web_api:
    image: mcr.microsoft.com/dotnet/sdk:8.0-alpine
    container_name: dotnet_api
    build:
      context: .
      dockerfile: Dockerfile
    command: dotnet watch
    working_dir: /app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://localhost:80
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    ports:
      - "5000:80"
    env_file:
      - .env
    volumes:
      - .:/app